spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/bookingdatabase?authSource=admin
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://db:5432/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS booking_schema
      connection-timeout: 10000
  kafka:
    bootstrap-servers: kafka:9092
app:
  kafka:
    kafkaMessageUserTopic: "kafka-user-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
    kafkaMessageBookingTopic: "kafka-booking-topic"